### ISSUE TITLE
Add the ability to delete text in the markdown.

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/onenote-markdown#48]
- [ ] Deletion on `<p>C</p>` resulting in an empty string should convert it to `<br />` (Note, `C` is any random content). #63
- [x] Deleting single characters using the Backspace key #59
    - [x] Fix for empty new lines
    - [x] Fix for populated new lines
- [ ] Deleting single characters using the Delete key #60
- [ ] Selecting multiple text, and deleting #61
- [ ] Selecting multiple text, and inputting new text #62

**Comment by dalyIsaac** [comment]
When deleting a character using Backspace, when the selection is the start of a `StructureNode`:

- if there **is no `StructureNode`s before the node** which has selection, then **nothing should happen**.
- if there **is a `StructureNode` before the node** which has selection, then the **two `StructureNode`s should be merged**.
